- name: install_pip_packages
  sudo: true
  with_items: pip_packages
  pip:
    name: "{{ item.name }}"
    executable: pip3

- name: create django project
  command: python3 /usr/local/bin/django-admin.py startproject "{{ nameOfProject }}" chdir= /vagrant
